[
    {
      "id": "s3://mockingbird-prod/abigail_vo_6661b91f-4012-44e3-ad12-589fbdee9948/voices/speaker/manifest.json",
      "name": "Abigail",
      "sample": "https://peregrine-samples.s3.us-east-1.amazonaws.com/editor-samples/abigail_vo.wav",
      "accent": "american",
      "age": null,
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": null,
      "style": "narrative",
      "tempo": null,
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "abram",
      "name": "Abram",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/abram.wav",
      "accent": "british",
      "age": "old",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "low",
      "style": "narrative",
      "tempo": "slow",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "adolfo",
      "name": "Adolfo",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/adolfo.wav",
      "accent": "american",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "fast",
      "texture": "thick",
      "is_cloned": false
    },
    {
      "id": "adrian",
      "name": "Adrian",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/Adrian.wav",
      "accent": "american",
      "age": "old",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "fast",
      "texture": "thick",
      "is_cloned": false
    },
    {
      "id": "ahmed",
      "name": "Logan",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/ahmed.wav",
      "accent": "british",
      "age": "old",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "thick",
      "is_cloned": false
    },
    {
      "id": "alex",
      "name": "Alex",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/alex.wav",
      "accent": "british",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "high",
      "style": "narrative",
      "tempo": "slow",
      "texture": "thick",
      "is_cloned": false
    },
    {
      "id": "alexander",
      "name": "Alexander",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/Alexander.wav",
      "accent": "british",
      "age": "old",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "high",
      "style": "narrative",
      "tempo": "fast",
      "texture": "thick",
      "is_cloned": false
    },
    {
      "id": "alfonso",
      "name": "Alfonso",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/alfonso.wav",
      "accent": "american",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "videos",
      "tempo": "neutral",
      "texture": "gravelly",
      "is_cloned": false
    },
    {
      "id": "alphonso",
      "name": "Alphonso",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/alphonso.wav",
      "accent": "american",
      "age": "adult",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "low",
      "style": "videos",
      "tempo": "neutral",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "amado",
      "name": "Amado",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/amado.wav",
      "accent": "american",
      "age": "old",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "low",
      "style": "narrative",
      "tempo": "fast",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "anny",
      "name": "Anny",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/anny.wav",
      "accent": "american",
      "age": "youth",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "thick",
      "is_cloned": false
    },
    {
      "id": "anthony",
      "name": "Anthony",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/Anthony.wav",
      "accent": "american",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "training",
      "tempo": "slow",
      "texture": "thick",
      "is_cloned": false
    },
    {
      "id": "spencer",
      "name": "April",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/spencer.wav",
      "accent": "british",
      "age": "adult",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "slow",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "victor",
      "name": "Ariana",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/victor.wav",
      "accent": "american",
      "age": "youth",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "high",
      "style": "videos",
      "tempo": "fast",
      "texture": "thick",
      "is_cloned": false
    },
    {
      "id": "arthur",
      "name": "Arthur",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/arthur.wav",
      "accent": "british",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "s3://peregrine-voices/arthur ads parrot saad/manifest.json",
      "name": "Arthur (Advertising)",
      "sample": "https://peregrine-samples.s3.amazonaws.com/parrot-samples/arthur+ads.wav",
      "accent": "british",
      "age": "adult",
      "gender": "male",
      "language": "English (GB)",
      "language_code": "en-GB",
      "loudness": "neutral",
      "style": "advertising",
      "tempo": "neutral",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "s3://mockingbird-prod/arthur_vo_meditatoin_211f702d-b185-4115-b8b4-801f8130a38d/voices/speaker/manifest.json",
      "name": "Arthur (Meditation)",
      "sample": "https://peregrine-samples.s3.us-east-1.amazonaws.com/editor-samples/arthur_vo_meditation.wav",
      "accent": "british",
      "age": "adult",
      "gender": "male",
      "language": "English (GB)",
      "language_code": "en-GB",
      "loudness": "neutral",
      "style": "meditation",
      "tempo": "neutral",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "s3://mockingbird-prod/arthur_vo_narrative_a33fd610-73a9-4401-9a78-6b8219c68a9e/voices/speaker/manifest.json",
      "name": "Arthur (Narrative)",
      "sample": "https://peregrine-samples.s3.us-east-1.amazonaws.com/editor-samples/arthur_vo_narrative.wav",
      "accent": "british",
      "age": "adult",
      "gender": "male",
      "language": "English (GB)",
      "language_code": "en-GB",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "s3://mockingbird-prod/arthur_vo_training_9281c8fd-c7f0-4445-a148-466292d3d329/voices/speaker/manifest.json",
      "name": "Arthur (Training)",
      "sample": "https://peregrine-samples.s3.us-east-1.amazonaws.com/editor-samples/arthur_vo_training.wav",
      "accent": "british",
      "age": "adult",
      "gender": "male",
      "language": "English (GB)",
      "language_code": "en-GB",
      "loudness": "neutral",
      "style": "training",
      "tempo": "neutral",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "aubrey",
      "name": "Aubrey",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/aubrey.wav",
      "accent": "british",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "videos",
      "tempo": "neutral",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "hipolito",
      "name": "Audrey",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/hipolito.wav",
      "accent": "american",
      "age": "adult",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "low",
      "style": "narrative",
      "tempo": "slow",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "aurora",
      "name": "Aurora",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/Aurora.wav",
      "accent": "british",
      "age": "adult",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "low",
      "style": "training",
      "tempo": "slow",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "axel",
      "name": "Axel",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/Axel.wav",
      "accent": "american",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "fast",
      "texture": "thick",
      "is_cloned": false
    },
    {
      "id": "s3://mockingbird-prod/ayla_vo_commercials_d66900d5-69f5-476f-9bd6-8eab2936dda3/voices/speaker/manifest.json",
      "name": "Ayla (Advertising)",
      "sample": "https://peregrine-samples.s3.us-east-1.amazonaws.com/editor-samples/ayla_vo_commercials.wav",
      "accent": "american",
      "age": null,
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": null,
      "style": "advertising",
      "tempo": null,
      "texture": null,
      "is_cloned": false
    },
    {
      "id": "s3://mockingbird-prod/ayla_vo_expressive_16095e08-b9e8-429b-947c-47a75e41053b/voices/speaker/manifest.json",
      "name": "Ayla (Expressive)",
      "sample": null,
      "accent": "american",
      "age": null,
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": null,
      "style": "narrative",
      "tempo": null,
      "texture": null,
      "is_cloned": false
    },
    {
      "id": "s3://mockingbird-prod/ayla_vo_meditation_d11dd9da-b5f1-4709-95a6-e6d5dc77614a/voices/speaker/manifest.json",
      "name": "Ayla (Meditation)",
      "sample": "https://peregrine-samples.s3.us-east-1.amazonaws.com/editor-samples/ayla_vo_meditation.wav",
      "accent": "american",
      "age": null,
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": null,
      "style": "meditation",
      "tempo": null,
      "texture": null,
      "is_cloned": false
    },
    {
      "id": "s3://mockingbird-prod/ayla_vo_narrative_d8199dfd-b50f-40c7-9d99-e203ba5f4152/voices/speaker/manifest.json",
      "name": "Ayla (Narrative)",
      "sample": "https://peregrine-samples.s3.us-east-1.amazonaws.com/editor-samples/ayla_vo_narrative.wav",
      "accent": "american",
      "age": null,
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": null,
      "style": "narrative",
      "tempo": null,
      "texture": null,
      "is_cloned": false
    },
    {
      "id": "s3://mockingbird-prod/ayla_vo_training_e6751ca5-e47c-4c4b-ad05-d3a194417600/voices/speaker/manifest.json",
      "name": "Ayla (Training)",
      "sample": "https://peregrine-samples.s3.us-east-1.amazonaws.com/editor-samples/ayla_vo_training.wav",
      "accent": "american",
      "age": null,
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": null,
      "style": "training",
      "tempo": null,
      "texture": null,
      "is_cloned": false
    },
    {
      "id": "s3://peregrine-voices/barry ads parrot saad/manifest.json",
      "name": "Barry (Advertising)",
      "sample": "https://peregrine-samples.s3.amazonaws.com/parrot-samples/barry+ads.wav",
      "accent": "australian",
      "age": null,
      "gender": "male",
      "language": "English (AU)",
      "language_code": "en-AU",
      "loudness": null,
      "style": "advertising",
      "tempo": null,
      "texture": null,
      "is_cloned": false
    },
    {
      "id": "s3://peregrine-voices/barry narrative parrot saad/manifest.json",
      "name": "Barry (Narrative)",
      "sample": "https://peregrine-samples.s3.amazonaws.com/parrot-samples/barry+narrative.wav",
      "accent": "australian",
      "age": null,
      "gender": "male",
      "language": "English (AU)",
      "language_code": "en-AU",
      "loudness": null,
      "style": "narrative",
      "tempo": null,
      "texture": null,
      "is_cloned": false
    },
    {
      "id": "benton",
      "name": "Benton",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/benton.wav",
      "accent": "american",
      "age": "old",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "high",
      "style": "videos",
      "tempo": "fast",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "bertram",
      "name": "Bertram",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/bertram.wav",
      "accent": "british",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "low",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "gravelly",
      "is_cloned": false
    },
    {
      "id": "bill",
      "name": "Harper",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/bill.wav",
      "accent": "american",
      "age": "adult",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "high",
      "style": "videos",
      "tempo": "fast",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "s3://mockingbird-prod/nathan_drake_carmelo_pampillonio_7d540ad6-7d32-41f6-8d53-2584901aa03d/voices/speaker/manifest.json",
      "name": "Billy",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/billy.wav",
      "accent": "american",
      "age": null,
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": null,
      "style": "gaming",
      "tempo": null,
      "texture": null,
      "is_cloned": false
    },
    {
      "id": "blaine",
      "name": "Blaine",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/blaine.wav",
      "accent": "british",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "high",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "thick",
      "is_cloned": false
    },
    {
      "id": "booker",
      "name": "Booker",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/booker.wav",
      "accent": "british",
      "age": "youth",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "bret",
      "name": "Bret",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/bret.wav",
      "accent": "american",
      "age": "adult",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "slow",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "bruce",
      "name": "Bruce",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/bruce.wav",
      "accent": "british",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "high",
      "style": "training",
      "tempo": "fast",
      "texture": "thick",
      "is_cloned": false
    },
    {
      "id": "bryan",
      "name": "Bryan",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/bryan.wav",
      "accent": "american",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "low",
      "style": "videos",
      "tempo": "fast",
      "texture": "gravelly",
      "is_cloned": false
    },
    {
      "id": "carlo",
      "name": "Carlo",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/carlo.wav",
      "accent": "british",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "advertising",
      "tempo": "neutral",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "carter",
      "name": "Carter",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/Carter.wav",
      "accent": "american",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "thick",
      "is_cloned": false
    },
    {
      "id": "charles",
      "name": "Charles",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/charles.wav",
      "accent": "american",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "charlotte",
      "name": "Charlotte",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/charlotte.wav",
      "accent": "canadian",
      "age": "adult",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "low",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "s3://peregrine-voices/charlotte ads parrot saad/manifest.json",
      "name": "Charlotte (Advertising)",
      "sample": "https://peregrine-samples.s3.amazonaws.com/parrot-samples/charlotte+ads.wav",
      "accent": "canadian",
      "age": "adult",
      "gender": "female",
      "language": "English (CA)",
      "language_code": "en-CA",
      "loudness": "low",
      "style": "advertising",
      "tempo": "neutral",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "s3://peregrine-voices/charlotte meditation 2 parrot saad/manifest.json",
      "name": "Charlotte (Meditation)",
      "sample": "https://peregrine-samples.s3.amazonaws.com/parrot-samples/charlotte+meditation.wav",
      "accent": "canadian",
      "age": "adult",
      "gender": "female",
      "language": "English (CA)",
      "language_code": "en-CA",
      "loudness": "low",
      "style": "meditation",
      "tempo": "neutral",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "s3://mockingbird-prod/charlotte_vo_narrative_9290be17-ccea-4700-a7fd-a8fe5c49fb20/voices/speaker/manifest.json",
      "name": "Charlotte (Narrative)",
      "sample": "https://peregrine-samples.s3.us-east-1.amazonaws.com/editor-samples/charlotte_vo_narrative.wav",
      "accent": "canadian",
      "age": "adult",
      "gender": "female",
      "language": "English (CA)",
      "language_code": "en-CA",
      "loudness": "low",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "s3://peregrine-voices/charlotte_training_parrot_saad/manifest.json",
      "name": "Charlotte (Training)",
      "sample": "https://peregrine-samples.s3.amazonaws.com/parrot-samples/charlotte+training.wav",
      "accent": "canadian",
      "age": "adult",
      "gender": "female",
      "language": "English (CA)",
      "language_code": "en-CA",
      "loudness": "low",
      "style": "training",
      "tempo": "neutral",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "chuck",
      "name": "Chuck",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/chuck.wav",
      "accent": "british",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "videos",
      "tempo": "slow",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "clark",
      "name": "Clark",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/clark.wav",
      "accent": "british",
      "age": "old",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "slow",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "clifton",
      "name": "Clifton",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/clifton.wav",
      "accent": "american",
      "age": "old",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "high",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "gravelly",
      "is_cloned": false
    },
    {
      "id": "hayden",
      "name": "Cooper",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/hayden.wav",
      "accent": "american",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "daisy",
      "name": "Daisy",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/Daisy.wav",
      "accent": "british",
      "age": "adult",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "low",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "gravelly",
      "is_cloned": false
    },
    {
      "id": "dane",
      "name": "Dane",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/dane.wav",
      "accent": "american",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "videos",
      "tempo": "neutral",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "daniel",
      "name": "Daniel",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/daniel_vo.wav",
      "accent": "canadian",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "low",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "darnell",
      "name": "Darnell",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/darnell.wav",
      "accent": "american",
      "age": "youth",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "daron",
      "name": "Daron",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/daron.wav",
      "accent": "american",
      "age": "old",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "low",
      "style": "narrative",
      "tempo": "slow",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "darrell",
      "name": "Darrell",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/darrell.wav",
      "accent": "british",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "advertising",
      "tempo": "neutral",
      "texture": "thick",
      "is_cloned": false
    },
    {
      "id": "ignacio",
      "name": "Delilah",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/ignacio.wav",
      "accent": "american",
      "age": "adult",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "slow",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "denis",
      "name": "Eleanor",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/denis.wav",
      "accent": "british",
      "age": "adult",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "advertising",
      "tempo": "neutral",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "dick",
      "name": "Dick",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/dick.wav",
      "accent": "american",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "training",
      "tempo": "fast",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "domenic",
      "name": "Domenic",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/domenic.wav",
      "accent": "british",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "high",
      "style": "videos",
      "tempo": "neutral",
      "texture": "thick",
      "is_cloned": false
    },
    {
      "id": "s3://peregrine-voices/donna_meditation_saad/manifest.json",
      "name": "Donna (Meditation)",
      "sample": "https://peregrine-samples.s3.amazonaws.com/parrot-samples/donna+meditation.wav",
      "accent": "american",
      "age": null,
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": null,
      "style": "meditation",
      "tempo": null,
      "texture": null,
      "is_cloned": false
    },
    {
      "id": "s3://peregrine-voices/donna_parrot_saad/manifest.json",
      "name": "Donna (Narrative)",
      "sample": "https://peregrine-samples.s3.amazonaws.com/parrot-samples/donna+narrative.wav",
      "accent": "american",
      "age": null,
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": null,
      "style": "narrative",
      "tempo": null,
      "texture": null,
      "is_cloned": false
    },
    {
      "id": "donovan",
      "name": "Donovan",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/donovan.wav",
      "accent": "american",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "low",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "dudley",
      "name": "Dudley",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/dudley.wav",
      "accent": "american",
      "age": "old",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "low",
      "style": "narrative",
      "tempo": "fast",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "dylan",
      "name": "Dylan",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/dylan.wav",
      "accent": "british",
      "age": "old",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "high",
      "style": "gaming",
      "tempo": "slow",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "earle",
      "name": "Earle",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/earle.wav",
      "accent": "british",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "high",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "gravelly",
      "is_cloned": false
    },
    {
      "id": "efren",
      "name": "Efren",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/efren.wav",
      "accent": "american",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "training",
      "tempo": "slow",
      "texture": "thick",
      "is_cloned": false
    },
    {
      "id": "s3://mockingbird-prod/eileen_vo_5d7b2bcc-d635-4301-97e8-d97c13768514/voices/speaker/manifest.json",
      "name": "Eileen",
      "sample": "https://peregrine-samples.s3.us-east-1.amazonaws.com/editor-samples/eileen_vo.wav",
      "accent": "british",
      "age": null,
      "gender": "female",
      "language": "English (GB)",
      "language_code": "en-GB",
      "loudness": null,
      "style": "narrative",
      "tempo": null,
      "texture": null,
      "is_cloned": false
    },
    {
      "id": "denis",
      "name": "Eleanor",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/denis.wav",
      "accent": "british",
      "age": "adult",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "advertising",
      "tempo": "neutral",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "elijah",
      "name": "Elijah",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/elijah.wav",
      "accent": "american",
      "age": "old",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "training",
      "tempo": "neutral",
      "texture": "gravelly",
      "is_cloned": false
    },
    {
      "id": "ellie",
      "name": "Ellie",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/Ellie.wav",
      "accent": "american",
      "age": "adult",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "low",
      "style": "training",
      "tempo": "slow",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "erasmo",
      "name": "Erasmo",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/erasmo.wav",
      "accent": "american",
      "age": "old",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "low",
      "style": "training",
      "tempo": "fast",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "s3://peregrine-voices/evelyn 2 saad parrot/manifest.json",
      "name": "Evelyn",
      "sample": "https://peregrine-samples.s3.amazonaws.com/parrot-samples/evelyn.wav",
      "accent": "american",
      "age": "adult",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "low",
      "style": "videos",
      "tempo": "neutral",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "fletcher",
      "name": "Fletcher",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/fletcher.wav",
      "accent": "british",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "fast",
      "texture": "gravelly",
      "is_cloned": false
    },
    {
      "id": "florencio",
      "name": "Madison",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/florencio.wav",
      "accent": "british",
      "age": "old",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "slow",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "flynn",
      "name": "Flynn",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/flynn.wav",
      "accent": "british",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "fast",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "frankie",
      "name": "Frankie",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/Frankie.wav",
      "accent": "american",
      "age": "old",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "training",
      "tempo": "neutral",
      "texture": "thick",
      "is_cloned": false
    },
    {
      "id": "frederick",
      "name": "Frederick",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/Frederick.wav",
      "accent": "british",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "low",
      "style": "narrative",
      "tempo": "slow",
      "texture": "thick",
      "is_cloned": false
    },
    {
      "id": "gabriel",
      "name": "Samantha",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/gabriel.wav",
      "accent": "american",
      "age": "old",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "thick",
      "is_cloned": false
    },
    {
      "id": "greg",
      "name": "Greg",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/greg.wav",
      "accent": "british",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "high",
      "style": "narrative",
      "tempo": "slow",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "harold",
      "name": "Harold",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/harold.wav",
      "accent": "american",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "slow",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "bill",
      "name": "Harper",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/bill.wav",
      "accent": "american",
      "age": "adult",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "high",
      "style": "videos",
      "tempo": "fast",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "harris",
      "name": "Harris",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/harris.wav",
      "accent": "british",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "low",
      "style": "narrative",
      "tempo": "fast",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "harrison",
      "name": "Harrison",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/Harrison.wav",
      "accent": "american",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "fast",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "hayden",
      "name": "Cooper",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/hayden.wav",
      "accent": "american",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "hipolito",
      "name": "Audrey",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/hipolito.wav",
      "accent": "american",
      "age": "adult",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "low",
      "style": "narrative",
      "tempo": "slow",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "s3://mockingbird-prod/hook_1_chico_a3e5e83f-08ae-4a9f-825c-7e48d32d2fd8/voices/speaker/manifest.json",
      "name": "Hook",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/hook.wav",
      "accent": "american",
      "age": null,
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": null,
      "style": "gaming",
      "tempo": null,
      "texture": null,
      "is_cloned": false
    },
    {
      "id": "s3://peregrine-voices/hudson saad parrot/manifest.json",
      "name": "Hudson",
      "sample": "https://peregrine-samples.s3.amazonaws.com/parrot-samples/hudson.wav",
      "accent": "american",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "videos",
      "tempo": "neutral",
      "texture": "thick",
      "is_cloned": false
    },
    {
      "id": "hunter",
      "name": "Hunter",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/Hunter.wav",
      "accent": "british",
      "age": "old",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "high",
      "style": "narrative",
      "tempo": "fast",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "ignacio",
      "name": "Delilah",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/ignacio.wav",
      "accent": "american",
      "age": "adult",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "slow",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "jarrett",
      "name": "Jarrett",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/jarrett.wav",
      "accent": "american",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "low",
      "style": "advertising",
      "tempo": "slow",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "jerrell",
      "name": "Jerrell",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/jerrell.wav",
      "accent": "american",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "low",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "jordan",
      "name": "Jordan",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/jordan.wav",
      "accent": "american",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "training",
      "tempo": "slow",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "judson",
      "name": "Judson",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/judson.wav",
      "accent": "american",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "low",
      "style": "narrative",
      "tempo": "slow",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "julian",
      "name": "Julian",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/Julian.wav",
      "accent": "american",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "videos",
      "tempo": "neutral",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "lance",
      "name": "Lance",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/lance.wav",
      "accent": "british",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "low",
      "style": "videos",
      "tempo": "neutral",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "larry",
      "name": "Larry",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/larry.wav",
      "accent": "american",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "s3://peregrine-voices/larry_ads3_parrot_saad/manifest.json",
      "name": "Larry (Advertising)",
      "sample": "https://peregrine-samples.s3.amazonaws.com/parrot-samples/larry+ads.wav",
      "accent": "american",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "advertising",
      "tempo": "neutral",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "s3://mockingbird-prod/larry_vo_narrative_4bd5c1bd-f662-4a38-b5b9-76563f7b92ec/voices/speaker/manifest.json",
      "name": "Larry (Narrative)",
      "sample": "https://peregrine-samples.s3.us-east-1.amazonaws.com/editor-samples/larry_vo_narrative.wav",
      "accent": "american",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "lillian",
      "name": "Lillian",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/Lillian.wav",
      "accent": "british",
      "age": "old",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "training",
      "tempo": "slow",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "ahmed",
      "name": "Logan",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/ahmed.wav",
      "accent": "british",
      "age": "old",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "thick",
      "is_cloned": false
    },
    {
      "id": "lottie",
      "name": "Lottie",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/Lottie.wav",
      "accent": "british",
      "age": "adult",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "low",
      "style": "narrative",
      "tempo": "slow",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "lucius",
      "name": "Lucius",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/lucius.wav",
      "accent": "british",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "low",
      "style": "narrative",
      "tempo": "slow",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "mickey",
      "name": "Madelyn",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/mickey.wav",
      "accent": "british",
      "age": "adult",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "videos",
      "tempo": "fast",
      "texture": "thick",
      "is_cloned": false
    },
    {
      "id": "florencio",
      "name": "Madison",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/florencio.wav",
      "accent": "british",
      "age": "old",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "slow",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "micah",
      "name": "Micah",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/micah.wav",
      "accent": "british",
      "age": "adult",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "mickey",
      "name": "Madelyn",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/mickey.wav",
      "accent": "british",
      "age": "adult",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "videos",
      "tempo": "fast",
      "texture": "thick",
      "is_cloned": false
    },
    {
      "id": "s3://peregrine-voices/nolan saad parrot/manifest.json",
      "name": "Nolan",
      "sample": "https://peregrine-samples.s3.amazonaws.com/parrot-samples/nolan.wav",
      "accent": "british",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "high",
      "style": "videos",
      "tempo": "neutral",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "nova",
      "name": "Nova",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/Nova.wav",
      "accent": "american",
      "age": "adult",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "whisper",
      "style": "narrative",
      "tempo": "slow",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "oliver",
      "name": "Oliver",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/oliver.wav",
      "accent": "british",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "high",
      "style": "videos",
      "tempo": "neutral",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "s3://peregrine-voices/oliver_ads2_parrot_saad/manifest.json",
      "name": "Oliver (Advertising)",
      "sample": "https://peregrine-samples.s3.amazonaws.com/parrot-samples/oliver+ads.wav",
      "accent": "british",
      "age": "adult",
      "gender": "male",
      "language": "English (GB)",
      "language_code": "en-GB",
      "loudness": "high",
      "style": "advertising",
      "tempo": "neutral",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "s3://peregrine-voices/oliver_narrative2_parrot_saad/manifest.json",
      "name": "Oliver (Narrative)",
      "sample": "https://peregrine-samples.s3.amazonaws.com/parrot-samples/oliver+narrative.wav",
      "accent": "british",
      "age": "adult",
      "gender": "male",
      "language": "English (GB)",
      "language_code": "en-GB",
      "loudness": "high",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "s3://mockingbird-prod/oliver_vo_training_6e3f604a-5605-4542-948d-347b0d7546fc/voices/speaker/manifest.json",
      "name": "Oliver (Training)",
      "sample": null,
      "accent": "british",
      "age": "adult",
      "gender": "male",
      "language": "English (GB)",
      "language_code": "en-GB",
      "loudness": "high",
      "style": "training",
      "tempo": "neutral",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "s3://mockingbird-prod/olivia_vo_commercials_6e3c384f-15d6-4fe7-b9a4-0cb1d69daeba/voices/speaker/manifest.json",
      "name": "Olivia (Advertising)",
      "sample": "https://peregrine-samples.s3.us-east-1.amazonaws.com/editor-samples/olivia_vo_commercials.wav",
      "accent": "canadian",
      "age": null,
      "gender": "female",
      "language": "English (CA)",
      "language_code": "en-CA",
      "loudness": null,
      "style": "advertising",
      "tempo": null,
      "texture": null,
      "is_cloned": false
    },
    {
      "id": "s3://peregrine-voices/olivia_ads3_parrot_saad/manifest.json",
      "name": "Olivia (Narrative)",
      "sample": "https://peregrine-samples.s3.amazonaws.com/parrot-samples/olivia+narrative.wav",
      "accent": "canadian",
      "age": null,
      "gender": "female",
      "language": "English (CA)",
      "language_code": "en-CA",
      "loudness": null,
      "style": "narrative",
      "tempo": null,
      "texture": null,
      "is_cloned": false
    },
    {
      "id": "s3://mockingbird-prod/olivia_vo_training_4376204f-a411-4e5d-a5c0-ce6cc3908052/voices/speaker/manifest.json",
      "name": "Olivia (Training)",
      "sample": "https://peregrine-samples.s3.us-east-1.amazonaws.com/editor-samples/olivia_vo_training.wav",
      "accent": "canadian",
      "age": null,
      "gender": "female",
      "language": "English (CA)",
      "language_code": "en-CA",
      "loudness": null,
      "style": "training",
      "tempo": null,
      "texture": null,
      "is_cloned": false
    },
    {
      "id": "oscar",
      "name": "Oscar",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/oscar.wav",
      "accent": "british",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "slow",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "owen",
      "name": "Owen",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/Owen.wav",
      "accent": "american",
      "age": "youth",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "high",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "pedro",
      "name": "Pedro",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/pedro.wav",
      "accent": "american",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "slow",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "phoebe",
      "name": "Phoebe",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/Phoebe.wav",
      "accent": "british",
      "age": "adult",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "high",
      "style": "videos",
      "tempo": "fast",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "randall",
      "name": "Randall",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/randall.wav",
      "accent": "british",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "high",
      "style": "narrative",
      "tempo": "fast",
      "texture": "thick",
      "is_cloned": false
    },
    {
      "id": "reynaldo",
      "name": "Reynaldo",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/reynaldo.wav",
      "accent": "british",
      "age": "old",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "low",
      "style": "narrative",
      "tempo": "fast",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "rodrick",
      "name": "Rodrick",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/rodrick.wav",
      "accent": "american",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "s3://peregrine-voices/russell2_parrot_saad/manifest.json",
      "name": "Russell",
      "sample": "https://peregrine-samples.s3.amazonaws.com/parrot-samples/russell.wav",
      "accent": "australian",
      "age": null,
      "gender": "male",
      "language": "English (AU)",
      "language_code": "en-AU",
      "loudness": null,
      "style": null,
      "tempo": null,
      "texture": null,
      "is_cloned": false
    },
    {
      "id": "gabriel",
      "name": "Samantha",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/gabriel.wav",
      "accent": "american",
      "age": "old",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "thick",
      "is_cloned": false
    },
    {
      "id": "samuel",
      "name": "Samuel",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/samuel.wav",
      "accent": "american",
      "age": "old",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "high",
      "style": "narrative",
      "tempo": "slow",
      "texture": "gravelly",
      "is_cloned": false
    },
    {
      "id": "s3://mockingbird-prod/agent_47_carmelo_pampillonio_58e796e1-0b87-4f3e-8b36-7def6d65ce66/voices/speaker/manifest.json",
      "name": "Sarge",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/sarge.wav",
      "accent": "american",
      "age": null,
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": null,
      "style": "gaming",
      "tempo": null,
      "texture": null,
      "is_cloned": false
    },
    {
      "id": "spencer",
      "name": "April",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/spencer.wav",
      "accent": "british",
      "age": "adult",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "slow",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "stella",
      "name": "Stella",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/Stella.wav",
      "accent": "british",
      "age": "old",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "training",
      "tempo": "slow",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "susan",
      "name": "Susan",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/susan.wav",
      "accent": "american",
      "age": "adult",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "high",
      "style": "videos",
      "tempo": "neutral",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "s3://mockingbird-prod/susan_vo_commercials_0f4fa663-6eba-4582-be1e-2d5bde798f1c/voices/speaker/manifest.json",
      "name": "Susan (Advertising)",
      "sample": "https://peregrine-samples.s3.us-east-1.amazonaws.com/editor-samples/susan_vo_commercials.wav",
      "accent": "american",
      "age": "adult",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "high",
      "style": "advertising",
      "tempo": "neutral",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "s3://mockingbird-prod/susan_vo_narrative_73051c90-460b-4e54-adab-9235f45c5e5f/voices/speaker/manifest.json",
      "name": "Susan (Narrative)",
      "sample": null,
      "accent": "american",
      "age": "adult",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "high",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "s3://mockingbird-prod/susan_vo_training_46ffcc60-d630-42f6-acfe-4affd003ae7a/voices/speaker/manifest.json",
      "name": "Susan (Training)",
      "sample": "https://peregrine-samples.s3.us-east-1.amazonaws.com/editor-samples/susan_vo_training.wav",
      "accent": "american",
      "age": "adult",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "high",
      "style": "training",
      "tempo": "neutral",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "theodore",
      "name": "Theodore",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/Theodore.wav",
      "accent": "american",
      "age": "old",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "gravelly",
      "is_cloned": false
    },
    {
      "id": "victor",
      "name": "Ariana",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/victor.wav",
      "accent": "american",
      "age": "youth",
      "gender": "female",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "high",
      "style": "videos",
      "tempo": "fast",
      "texture": "thick",
      "is_cloned": false
    },
    {
      "id": "wilbert",
      "name": "Wilbert",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/wilbert.wav",
      "accent": "british",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "wilbur",
      "name": "Wilbur",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/wilbur.wav",
      "accent": "american",
      "age": "youth",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "wilfred",
      "name": "Wilfred",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/wilfred.wav",
      "accent": "american",
      "age": "old",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "low",
      "style": "training",
      "tempo": "slow",
      "texture": "smooth",
      "is_cloned": false
    },
    {
      "id": "william",
      "name": "William",
      "sample": "https://peregrine-samples.s3.amazonaws.com/editor-samples/william_vo.wav",
      "accent": "american",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "videos",
      "tempo": "neutral",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "s3://mockingbird-prod/william_vo_narrative_0eacdff5-6243-4e26-8b3b-66e03458c1d1/voices/speaker/manifest.json",
      "name": "William (Narrative)",
      "sample": "https://peregrine-samples.s3.us-east-1.amazonaws.com/editor-samples/william_vo_narrative.wav",
      "accent": "american",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "narrative",
      "tempo": "neutral",
      "texture": "round",
      "is_cloned": false
    },
    {
      "id": "s3://mockingbird-prod/william_vo_training_1b939b71-14fa-41f0-b1db-7d94f194ad0a/voices/speaker/manifest.json",
      "name": "William (Training)",
      "sample": "https://peregrine-samples.s3.us-east-1.amazonaws.com/editor-samples/william_vo_training.wav",
      "accent": "american",
      "age": "adult",
      "gender": "male",
      "language": "English (US)",
      "language_code": "en-US",
      "loudness": "neutral",
      "style": "training",
      "tempo": "neutral",
      "texture": "round",
      "is_cloned": false
    }
  ]